# Generated by Django 4.2.7 on 2024-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.CharField(
                choices=[("good", "Good Review"), ("bad", "Bad Review")],
                default="good",
                max_length=4,
                verbose_name="리뷰 종류",
            ),
        ),
    ]
