# Generated by Django 4.2.7 on 2024-10-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_review_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="review_type",
        ),
    ]
