# Generated by Django 4.2.7 on 2024-10-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_rename_review_review_review_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_type",
            new_name="review_category",
        ),
    ]
