# Generated by Django 4.2.7 on 2024-10-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_rename_review_type_review_review_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(
                default="Unknown", max_length=200, verbose_name="주소"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(default="Unknown", verbose_name="설명"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_name_en",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="레스토랑영문명"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="review_count",
            field=models.BigIntegerField(default=0, verbose_name="리뷰수"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="style",
            field=models.CharField(
                default="Unknown", max_length=200, verbose_name="스타일"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="url",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="catchtable_url"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.CharField(max_length=50, verbose_name="가격"),
        ),
    ]
